---

 server:
     port: 8088
 spring:
     application:
              name: customer-management-service

 eureka:
     client:
         service-url:
                  default-zone: http://localhost:8761/eureka
     instance:
       leaseRenewalIntervalInSeconds: 1
       leaseExpirationDurationInSeconds: 2
 ribbon:
  eureka:
    enabled: true

...